# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "88f6b1b891090832ebade07bf9e2ff71"
application_url = "https://jul-wal-issued-margin.trycloudflare.com"
embedded = true
name = "ceely-quick-tag"
handle = "ceely-quick-tag"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_inventory,write_locations,write_inventory,write_products,read_orders,write_orders,read_customers"

[auth]
redirect_urls = [
  "https://jul-wal-issued-margin.trycloudflare.com/auth/callback",
  "https://jul-wal-issued-margin.trycloudflare.com/auth/shopify/callback",
  "https://jul-wal-issued-margin.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "ceely-software-dev.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
